services:
  ocr-service:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    volumes:
      - ./:/app
    # command: ["python", "src/app.py"]
    command: ["flask", "run", "--host=0.0.0.0", "--port=3003"]
    environment:
      FLASK_APP: src/app.py
      FLASK_DEBUG: True
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3003/health"]
      interval: 5s
      timeout: 5s
      retries: 5