services:
  api-gateway:
    build: ./
    ports:
      - '8000:8000'
    volumes:
      - ./:/app
    command: npm run dev:no-debug
    depends_on:
      auth-service:
        condition: service_healthy
      user-service:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8000/health']
      interval: 10s
      timeout: 10s
      retries: 5
