services:
  api-gateway:
    build: ./
    ports:
      - '8000:8000'
      - '9228:9229' # デバッグポート
    volumes:
      - ./:/app
    # command: npm run dev
    command: node --inspect=0.0.0.0:9229 src/index.js #デバッグ用
    # depends_on:
    #   auth-service:
    #     condition: service_healthy
    #   user-service:
    #     condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8000/health']
      interval: 30s
      timeout: 10s
      retries: 5
