services:
  user-service:
    build: ./
    ports:
      - '3002:3002'
    volumes:
      - ./:/app
    command: npm run start
    depends_on:
      db_user_postgres:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3002/health']
      interval: 10s
      timeout: 10s
      retries: 5

  db_user_postgres:
    image: postgres:16-alpine
    container_name: sample_user_postgres
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5433:5432'
    volumes:
      - user_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U user -d user_db']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  user_postgres_data:
