openapi: 3.0.0
info:
  title: ユーザーサービスAPI
  version: 1.0.0
  description: ユーザーの詳細情報を管理するためのAPI
servers:
  - url: http://localhost:3002
    description: ユーザーサービスのサーバ
paths:
  /health:
    get:
      summary: サービスヘルスチェック
      responses:
        '200':
          description: ユーザーサービスは正常に動作しています！
  /users:
    post:
      summary: 新しいユーザーデータを作成
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                auth_user_id:
                  type: integer
                  description: 認証サービスからのID
                name:
                  type: string
                  maxLength: 100
                email:
                  type: string
                  format: email
                  maxLength: 100
              required:
                - auth_user_id
      responses:
        '201':
          description: ユーザーデータが正常に作成されました
        '400':
          description: 無効な入力値
        '409':
          description: ユーザーデータは既に存在します
  /users/{authUserId}:
    get:
      summary: 認証ユーザーIDでユーザーデータを取得
      parameters:
        - name: authUserId
          in: path
          required: true
          schema:
            type: integer
          description: 認証サービスからのユーザーID
      responses:
        '200':
          description: ユーザーデータを正常に取得しました
        '404':
          description: ユーザーが見つかりません
