services:
  auth-service:
    build: ./
    ports:
      - '3001:3001'
      # - '9229:9229' # デバッグポート
    volumes:
      - ./:/app
    command: npm run dev
    # command: node --inspect=0.0.0.0:9229 src/index.js #デバッグ用
    depends_on:
      db_auth_postgres:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3001/health']
      interval: 10s
      timeout: 10s
      retries: 5

  db_auth_postgres:
    image: postgres:16-alpine
    container_name: sample_auth_postgres
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U user -d auth_db']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  auth_postgres_data:
