### 起動チェック
GET http://localhost:3003/health

### テキスト抽出1
POST http://localhost:3003/extract
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="image.png"
Content-Type: image/png

< ./sample/image.png
--WebAppBoundary--


### 画像テキスト抽出2(手書き)
POST http://localhost:3003/extract
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="image2.jpg"
Content-Type: image/jpg

< ./sample/image2.jpg
--WebAppBoundary--

### テキスト抽出(ライト画像)
POST http://localhost:3003/extract
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="light.png"
Content-Type: image/png

< ./sample/light.png
--WebAppBoundary--

### テキスト抽出（ダーク画像）
POST http://localhost:3003/extract
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="dark.png"
Content-Type: image/png

< ./sample/dark.png
--WebAppBoundary--