### 起動チェック
GET http://localhost:3003/health

### テキスト抽出（カスタム言語指定）
POST http://localhost:3003/extract
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="seikyu.png"
Content-Type: image/png

< ./sample/seikyu.png
--WebAppBoundary
Content-Disposition: form-data; name="regions"
Content-Type: application/json

[
     { "label": "No", "x": 620, "y": 80, "width": 165, "height": 25 },
     { "label": "請求日", "x": 620, "y": 100, "width": 165, "height": 25 }
]
--WebAppBoundary
Content-Disposition: form-data; name="lang"
Content-Type: text/plain

jpn
--WebAppBoundary--